# -*- coding: utf-8 -*-
"""pPenguin3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yx4swDMl7A1Pwarpmei3LCjB8fiyBsdu
"""

# PalmerPenguinM3.py
# Russell Thompson
# 10/05/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics

import math

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# constrants for number of penguins
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# list of species names
species_names = [SP_CHINSTRAP, SP_GENTOO, SP_ADELIE]

# list of species counts
species_counts = [NUM_CHINSTRAP, NUM_GENTOO, NUM_ADELIE]

# determine the number of species
total_species = len(species_names)

# calculate the total number of penguins
total_penguins = sum(species_counts)

# calculate the average number of penguins per species
average_penguins = total_penguins / total_species

# calculate the rounded-up average
average_penguins_rounded_up = math.ceil(average_penguins)

# calculate the species percentages
chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

# find the species with most and fewest observations
largest_count = max(species_counts)
smallest_count = min(species_counts)

# where do values occur
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

# use indexes to retrieve the corresponding species names:
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print()
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print(f"There are a total of {total_species} penguin species in this dataset.")


# display details of penguins averages
print(f"There are a total {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is {average_penguins:.1f}.")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")
print()

# number of penguins
print(f"{species_names[0]}: {species_counts[0]}"
   f" ({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_counts[1]}"
   f" ({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_counts[2]}"
   f" ({adelie_percent:.2f}%)")
print()

# penguin observations
print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the most observations is {smallest_species} with {smallest_count} penguins.")

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!git config --global user.email "s2945548@students.fscj.edu"
!git config --global user.email "Russmore44"

!git clone https://Russmore44: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@github.com/Russmore44/Mod1PA.git

!mv /content/screenshot.png/content/Mod1PA/

# %cd Mod1PA
!git add screenshot.png
!git commit -m "Upload colab screenshot"
!git push origin main